name: Deploy to Remote Server con docker-compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Copy SSH private key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH to Remote Server and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no username@your-server-ip-address 'cd /path/to/your/app && docker-compose pull && docker-compose up -d'
