version: '3.8'

services:
  app:
    container_name: laravel-app
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      # Agregar otras variables de entorno según sea necesario

  queue:
    container_name: laravel-queue
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work --queue=default'
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: laravel-db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: laravel_password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

networks:
  laravel-exa:
    driver: bridge

volumes:
  db-data:
